name: projeto_template
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6       
  json_serializable: ^6.8.0     #https://pub.dev/packages/json_serializable
  flutter_mobx: ^2.2.1+1        #https://pub.dev/packages/flutter_mobx
  mobx: ^2.3.3+2                #https://pub.dev/packages/mobx

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0         
  mobx_codegen: ^2.6.1          #https://pub.dev/packages/mobx_codegen
  build_runner: ^2.4.11         #https://pub.dev/packages/build_runner

flutter:

  uses-material-design: true

  # assets:

scripts: scripts.yaml
